// Explanations for the BTC Dashboard cards. Same shape and tone as explain.js:
// what it measures, why it matters, and the limits of the data. No predictions.

export const DASH_EXPLAIN = {
  d_price: {
    title: 'Live price',
    what: 'The last traded Bitcoin price in US dollars, polled every 10 seconds from Coinbase, with Binance, CoinGecko and Kraken as fallbacks.',
    why: 'It is the single number every other figure on this page is measured against.',
    caveat: () => 'Different exchanges trade a few dollars apart at any moment; the badge shows which one is in use and when it last updated.',
  },
  d_hilo: {
    title: '24-hour high and low',
    what: 'The highest and lowest prices traded on the live source exchange over the last 24 hours.',
    why: 'The range shows how much ground price covered in a day — a quick read of how calm or busy the market is.',
    caveat: () => 'Single-exchange figures; another venue’s extremes can differ slightly.',
  },
  d_vol24: {
    title: '24-hour volume',
    what: 'How much Bitcoin changed hands on the live source exchange over the last 24 hours, converted to dollars at the current price.',
    why: 'Rising volume alongside a move suggests more participation; thin volume means fewer trades are setting the price.',
    caveat: () => 'This is one exchange, not the whole market. The chart’s volume bars use CoinGecko’s cross-exchange total instead.',
  },
  d_mcap: {
    title: 'Market capitalisation',
    what: 'The live price multiplied by the number of bitcoins issued so far (computed from the current block height).',
    why: 'It puts Bitcoin’s size in context next to companies, gold or other assets.',
    caveat: () => 'Includes coins that are lost or have not moved in many years, so it overstates what could actually be traded.',
  },
  d_dom: {
    title: 'Bitcoin dominance',
    what: 'Bitcoin’s share of the total value of all crypto assets tracked by CoinGecko.',
    why: 'A rising share usually means money is favouring Bitcoin over smaller coins; a falling share means the opposite.',
    caveat: () => 'The total depends on which coins CoinGecko counts, including stablecoins, so different sites show different numbers.',
  },
  d_ath: {
    title: 'Distance from all-time high',
    what: 'How far the live price is below (or above) the highest price ever recorded, and when that high was set.',
    why: 'It frames where today’s price sits within the history of the asset.',
    caveat: () => 'The all-time high comes from CoinGecko’s aggregate price; single exchanges may show slightly different peaks.',
  },
  d_ma200: {
    title: '200-day moving average',
    what: 'The average daily closing price over the last 200 days, and how far the current price is from it.',
    why: 'Widely watched as a dividing line between long-term uptrends and downtrends.',
    caveat: () => 'A moving average follows price; it describes the trend so far rather than what comes next.',
  },
  d_range52: {
    title: '52-week range',
    what: 'The lowest and highest daily prices over the last year.',
    why: 'Shows where today’s price sits between the year’s extremes.',
  },
  d_rv: {
    title: 'Realised volatility (30 days)',
    what: 'How much the price has actually moved day to day over the last 30 days, expressed as an annual percentage.',
    why: 'Higher numbers mean bigger daily swings. Bitcoin has typically ranged between about 30% and 80%.',
    caveat: () => 'Backward-looking: it measures past movement, not expected movement.',
  },
  d_height: {
    title: 'Latest block',
    what: 'The newest block added to the Bitcoin blockchain, and how long ago it was found (from the block’s own timestamp). Each block confirms a batch of transactions; click the height or any recent block to open it on mempool.space.',
    why: 'It is Bitcoin’s clock: rewards, halvings and difficulty changes are all scheduled by block height, not by date.',
    caveat: () => 'Checked every 20 seconds from mempool.space, with blockstream.info and blockchain.info as fallbacks. Block timestamps are set by miners and can be off by a few minutes.',
  },
  d_blocktime: {
    title: 'Time since last block',
    what: 'How long ago the most recent block was found. Bitcoin targets one block every 10 minutes on average.',
    why: 'Gaps vary naturally; a 30-minute wait is not unusual and does not indicate a problem.',
    caveat: () => 'Block finding is random, like rolling dice, so individual gaps tell you little on their own.',
  },
  d_hashrate: {
    title: 'Hash rate',
    what: 'An estimate of the total computing power securing the network, in exahashes per second (billions of billions of guesses each second).',
    why: 'A higher hash rate makes the network more expensive to attack and reflects miners’ willingness to invest.',
    caveat: () => 'Hash rate cannot be measured directly; it is estimated from how quickly blocks are being found, so short-term readings are noisy.',
  },
  d_difficulty: {
    title: 'Mining difficulty',
    what: 'How hard it is to find a valid block. It resets every 2,016 blocks (about two weeks) to keep blocks arriving roughly every 10 minutes.',
    why: 'Difficulty rises when more miners join and falls when they leave, so it is a slow, reliable measure of mining competition.',
  },
  d_nextadj: {
    title: 'Next difficulty adjustment',
    what: 'The estimated change at the next difficulty reset, based on how fast blocks have arrived so far in this period.',
    why: 'An upward adjustment means miners face more competition; a downward one eases pressure on them.',
    caveat: () => 'An estimate that moves as blocks arrive; it is final only at the adjustment block.',
  },
  d_fees: {
    title: 'Fee rates',
    what: 'The fee, in satoshis per virtual byte, that mempool.space estimates is needed for a transaction to confirm within about 10 minutes, 30 minutes or an hour.',
    why: 'Fees rise when many people want block space at once, so they are a live gauge of on-chain demand.',
    caveat: () => 'Estimates only; actual confirmation depends on what other users bid after you send.',
  },
  d_txcost: {
    title: 'Typical transaction cost',
    what: 'The dollar cost of a simple transaction (about 140 virtual bytes) at the 30-minute fee rate.',
    why: 'Turns fee rates into a figure that is easier to relate to.',
    caveat: () => 'Larger transactions, such as those with many inputs, cost proportionally more.',
  },
  d_mempool: {
    title: 'Mempool',
    what: 'The waiting room of transactions that have been broadcast but not yet included in a block.',
    why: 'A growing backlog means demand for block space exceeds supply, which pushes fees up.',
    caveat: () => 'Each node keeps its own mempool; these figures are from mempool.space’s nodes.',
  },
  d_feeshare: {
    title: 'Fees as a share of miner revenue',
    what: 'The portion of miners’ income over the last 144 blocks (about one day) that came from transaction fees rather than newly created coins.',
    why: 'As the block reward halves every four years, fees need to carry more of the cost of securing the network over time.',
  },
  d_hashprice: {
    title: 'Hashprice',
    what: 'The expected daily revenue, in dollars, for each petahash per second of mining power — what a unit of mining work earns. Shown from CloudMineCrypto with 90 days of history; BTC Intel’s own figure from mempool.space data is shown alongside as a cross-check.',
    why: 'It is the miner’s “price per unit of work”; when it falls, less efficient miners come under pressure.',
    caveat: () => 'Different providers use slightly different averaging windows, so small differences between the two figures are normal.',
  },
  d_supply: {
    title: 'Issued supply',
    what: 'The number of bitcoins created so far, calculated from the current block height and Bitcoin’s fixed issuance schedule.',
    why: 'Supply is capped at 21 million, and the schedule is known in advance — one of Bitcoin’s defining features.',
    caveat: () => 'The schedule figure is slightly higher than coins that can actually be spent (a few early rewards were never claimable, and some coins are lost).',
  },
  d_inflation: {
    title: 'Annual issuance rate',
    what: 'New coins created per year at the current block reward, as a percentage of the supply already issued.',
    why: 'It shows how much new supply enters the market each year; it halves at every halving.',
  },
  d_exsupply: {
    title: 'Coins on exchanges',
    what: 'Coin Metrics’ estimate of how many bitcoins sit in wallets it attributes to exchanges.',
    why: 'Coins on exchanges are easier to sell quickly; a falling balance is often read as coins moving into longer-term storage.',
    caveat: () => 'Based on address labelling, which is incomplete and can shift when exchanges reorganise wallets. The latest days are early (“flash”) estimates.',
  },
  d_halving: {
    title: 'Next halving',
    what: 'Every 210,000 blocks the reward for mining a block is cut in half. The next one is at block 1,050,000, when it falls from 3.125 to 1.5625 BTC.',
    why: 'Halvings reduce the flow of new coins. Past halvings in 2012, 2016, 2020 and 2024 are often discussed alongside Bitcoin’s market cycles.',
    caveat: () => 'The date is an estimate (blocks remaining × recent average block time) and shifts as the hash rate changes.',
    reminder: true,
  },
  d_exflow: {
    title: 'Exchange net flow',
    what: 'Coins sent to exchanges minus coins withdrawn from them, per day, as estimated by Coin Metrics.',
    why: 'Net inflows can mean holders are preparing to sell; net outflows can mean coins are moving to long-term storage.',
    caveat: () => 'Address labelling is incomplete, internal exchange transfers can look like flows, and the latest days are early estimates.',
  },
  d_oi: {
    title: 'Futures open interest',
    what: 'The total value of Bitcoin futures and perpetual contracts that are open on the venues we can read for free.',
    why: 'More open contracts mean more borrowed money in the market, which can amplify moves when positions are forced to close.',
    caveat: () => 'Covers the listed venues, not the whole market; a wider CoinGecko total is shown underneath when available.',
  },
  d_funding: {
    title: 'Funding rate',
    what: 'The periodic payment between long and short holders of perpetual futures, shown as an annual rate averaged across venues.',
    why: 'Positive funding means longs pay shorts — bullish positioning is crowded. Negative means the reverse.',
    caveat: () => 'It changes every few hours and differs by venue.',
  },
  d_options: {
    title: 'Options open interest and implied volatility',
    what: 'The value of open Bitcoin options on Deribit, and DVOL — the volatility options traders are pricing for the next 30 days.',
    why: 'Higher implied volatility means traders are paying more for protection or upside.',
    caveat: () => 'Deribit is the largest crypto options venue but excludes CME and ETF options.',
  },
  d_liqsample: {
    title: 'Recent liquidations (sample)',
    what: 'Leveraged positions that exchanges force-closed, from OKX’s public feed for its BTC-USDT perpetual at the last server run.',
    why: 'Bursts of liquidations show where leverage was concentrated and can accelerate a move.',
    caveat: () => 'A single-venue sample. Market-wide liquidation totals are only available from paid providers, so they are not shown.',
  },
  d_etf: {
    title: 'Spot ETF flows',
    what: 'Net dollars created into (or redeemed from) US spot Bitcoin ETFs, from Farside Investors’ daily table.',
    why: 'ETF creations require buying the underlying bitcoin, so sustained flows are a direct source of demand or supply.',
    caveat: () => 'Published after the US close; some funds report a day late. Total ETF holdings are not shown because no free source publishes them reliably.',
  },
  d_treasury: {
    title: 'Public company treasuries',
    what: 'Bitcoin held by publicly listed companies, as compiled by CoinGecko from company disclosures.',
    why: 'Corporate buying has become a meaningful source of demand, and concentrated holders matter for supply.',
    caveat: () => 'Updated when companies disclose purchases, which can lag actual buying.',
  },
  d_active: {
    title: 'Active addresses',
    what: 'The number of distinct Bitcoin addresses that sent or received coins on a given day.',
    why: 'A rough gauge of how much the network is being used; sustained rises usually come with more interest and activity.',
    caveat: () => 'One person or exchange can use many addresses, and batching can hide users, so this counts addresses, not people.',
  },
  d_txcount: {
    title: 'Transactions per day',
    what: 'How many transactions were confirmed on the Bitcoin blockchain in a day.',
    why: 'Shows demand for block space. More transactions usually mean more competition and higher fees.',
    caveat: () => 'Exchanges often batch many payments into one transaction, so the count understates the number of payments.',
  },
  d_transfers: {
    title: 'Transfers per day',
    what: 'The number of individual payments (transaction outputs that move value) per day, as counted by Coin Metrics.',
    why: 'Counts payments inside batched transactions too, so it is a fuller picture of activity than the transaction count alone.',
    caveat: () => 'Includes change sent back to the sender, so it is not a count of distinct payments between people.',
  },
  d_addrbal: {
    title: 'Addresses holding BTC',
    what: 'How many Bitcoin addresses hold any amount above zero.',
    why: 'A slow-moving indicator of how widely coins are spread across wallets.',
    caveat: () => 'People often hold coins across many addresses, and exchanges pool customers into a few, so this is not a count of owners.',
  },
  d_feesday: {
    title: 'Fees paid per day',
    what: 'The total transaction fees, in bitcoin, that users paid to miners in a day.',
    why: 'Fees are what will pay for network security as the block reward keeps halving. High fees mean busy block space.',
  },
  d_minerrev: {
    title: 'Miner revenue',
    what: 'What miners earned over the last 144 blocks (about one day): newly issued coins plus transaction fees, valued at today’s price.',
    why: 'Miner income drives how much computing power secures the network; sharp drops can force weaker miners to sell coins or switch off machines.',
  },
  d_pools: {
    title: 'Mining pool concentration',
    what: 'The share of blocks found by each mining pool over the last week.',
    why: 'Bitcoin’s security relies on no single party controlling most of the mining power. High concentration in a few pools is worth watching.',
    caveat: () => 'Pools are groups of many independent miners who can switch pools, so pool share is not the same as ownership of the machines.',
  },
  d_sthrp: {
    title: 'Short-term holder realised price',
    what: 'The average price at which coins that moved in roughly the last five months were acquired — the cost basis of recent buyers.',
    why: 'When the market price is above it, recent buyers are in profit on average; when below, they are underwater, which has often coincided with stress.',
    caveat: () => 'From BGeometrics’ free tier, which runs about a week behind. Holder groups are estimated from how long coins have sat unmoved.',
    reminder: true,
  },
  d_lthrp: {
    title: 'Long-term holder realised price',
    what: 'The average price at which coins held longer than about five months were acquired — the cost basis of patient holders.',
    why: 'It moves slowly and has historically sat well below the market price except near deep bear-market lows.',
    caveat: () => 'From BGeometrics’ free tier, about a week behind. Holder groups are estimated from coin age, not from known identities.',
    reminder: true,
  },
  d_basis: {
    title: 'Futures basis',
    what: 'How much more (or less) a dated futures contract costs than spot bitcoin, expressed as an annual rate.',
    why: 'A higher premium means traders pay up to hold leveraged long exposure; a negative basis is rare and signals stress.',
  },
  d_dvol: {
    title: 'Implied volatility (DVOL)',
    what: 'Deribit’s index of how much price movement options traders expect over the next 30 days, as an annual percentage.',
    why: 'Low readings mean options are cheap and the market expects calm; sudden jumps often accompany large moves.',
    caveat: () => 'Reflects Deribit options only.',
  },
  d_ivrv: {
    title: 'Implied minus realised volatility',
    what: 'The volatility options traders are pricing for the next 30 days minus the volatility the price has actually shown over the past 30 days.',
    why: 'Negative means options are priced for less movement than recently seen (cheap protection); positive means traders expect more turbulence.',
  },
  d_dvs: {
    title: 'Derivatives vs spot volume',
    what: 'How many dollars of futures and perpetual contracts traded for every dollar of spot bitcoin, over the last 24 hours.',
    why: 'A high ratio means price is being driven more by leveraged trading than by buying and selling of actual coins.',
    caveat: () => 'Covers the venues we can read for free, not every exchange.',
  },
  d_treasconc: {
    title: 'Treasury concentration',
    what: 'How much of all bitcoin held by listed companies sits with the single largest holder, and with the top five.',
    why: 'When one company holds most corporate bitcoin, its decisions matter more for supply than the headline total suggests.',
  },
  d_ls: {
    title: 'Long/short account ratio',
    what: 'On OKX, the number of trader accounts holding net long BTC futures positions divided by those holding net shorts.',
    why: 'Shows how retail traders lean. Very lopsided readings have often been followed by moves against the crowd.',
    caveat: () => 'Counts accounts, not money: one large short can outweigh many small longs. One exchange only.',
  },
  d_cbprem: {
    title: 'Coinbase premium',
    what: 'The difference between bitcoin’s price on Coinbase (US dollars) and the average price on large USDT-quoted exchanges.',
    why: 'A positive premium suggests stronger buying from US investors and institutions, who mostly trade on Coinbase.',
    caveat: () => 'Small premiums (a few hundredths of a percent) are normal noise between venues.',
  },
  d_pcr: {
    title: 'Put/call ratio',
    what: 'The number of open put options (bets on or protection against falls) for every open call option (bets on rises) on Deribit.',
    why: 'A low ratio means traders hold more upside bets; a high ratio means more protection against declines.',
    caveat: () => 'Puts are often bought as insurance by holders, so a high ratio is not always bearish.',
  },
  d_skew: {
    title: '25-delta skew',
    what: 'The difference in price (implied volatility) between comparable call and put options about a month out. Negative means puts cost more than calls.',
    why: 'It shows whether traders are paying more for downside protection or for upside exposure.',
    caveat: () => 'Deribit options only; skew can swing quickly around large expiries.',
  },
  d_breadth: {
    title: 'Altcoin breadth vs BTC',
    what: 'The share of the 50 largest coins (excluding stablecoins) that did better than Bitcoin over the last 7 days.',
    why: 'Low breadth means money is concentrated in Bitcoin; high breadth means speculation is spreading to smaller coins.',
  },
  d_chart: {
    title: 'Price chart',
    what: 'Bitcoin’s price with its 50-, 100- and 200-day moving averages and a volatility envelope. Pick a timeframe from one hour to the full history.',
    why: 'Averages show the trend at different speeds; the envelope shows how far price has recently strayed from its short-term average.',
    caveat: () => 'Daily views use completed daily closes (Coin Metrics); the 1-hour, 1-day and 7-day views use Coinbase candles and show today’s daily averages and bands as flat reference lines.',
  },
  d_sma: {
    title: 'Moving averages (50, 100, 200 days)',
    what: 'The average daily closing price over the last 50, 100 or 200 days, recalculated each day.',
    why: 'They smooth out daily noise. Price above a rising average is the usual definition of an uptrend; the 200-day is the most widely watched.',
    caveat: () => 'Averages follow price, so they always lag turning points.',
  },
  d_envelope: {
    title: 'Volatility envelope (±2σ)',
    what: 'A band drawn 2 standard deviations above and below the 20-day average of daily closes (the classic Bollinger Band setting). Standard deviation measures how spread out the last 20 closes were.',
    why: 'When recent moves are small the band narrows; after big swings it widens. Price near a band edge has moved unusually far from its recent average.',
    caveat: () => 'It describes recent volatility, not a prediction: price can ride along a band edge for weeks in a strong trend.',
  },
  d_polymarket: {
    title: 'Prediction markets',
    what: 'Polymarket lets people trade contracts that pay $1 if an event happens. The price of “Yes” — say 38¢ — is the crowd’s implied probability, about 38%.',
    why: 'It shows how traders with money at stake currently weigh different price outcomes by a given date.',
    caveat: () => 'These are market-implied probabilities from Polymarket, not forecasts from BTC Intel. Thinly traded strikes can be noisy, and the markets resolve on specific exchange prices described on Polymarket.',
  },
  d_dist: {
    title: 'Address & coin distribution',
    what: 'All Bitcoin addresses with a balance, grouped by size: shrimp under 1 BTC, crabs 1–10, fish 10–100, sharks 100–1,000, whales 1,000–10,000 and humpbacks above 10,000 — with the coins each group holds.',
    why: 'Shifts between groups hint at whether coins are spreading out or concentrating, and the large groups show how much supply sits in big wallets.',
    caveat: () => 'Addresses are not people. Exchanges and ETF custodians hold many users’ coins in a few huge addresses, which inflates the whale and humpback groups. Source: bitinfocharts’ public table, captured once a day.',
  },
  d_corr: {
    title: 'Rolling correlation',
    what: 'How closely Bitcoin’s daily returns moved with another market over the last 30 (or 90) trading days, from −1 (opposite) through 0 (unrelated) to +1 (together).',
    why: 'It shows whether Bitcoin is currently trading like a risk asset, like a hedge, or on its own drivers.',
    caveat: () => 'Co-movement, not causation. Correlations shift often and are computed only over days when both markets traded.',
  },
  d_read: {
    title: 'Today’s read',
    what: 'Up to three short observations picked automatically from the figures on this page by fixed rules — for example where price sits in its volatility envelope, or an unusual reading in sentiment or ETF flows.',
    why: 'A quick orientation before reading the details.',
    caveat: () => 'Context, not a forecast or advice. The rules only pick and describe; they do not judge what will happen next.',
  },
  d_posture: {
    title: 'Market read',
    what: 'A one-word summary — Constructive, Neutral or Cautious — from seven fixed rules applied to figures already on this page. Each rule scores +1, 0 or −1: price vs the 200-day average; 50-day vs 200-day average; price vs the 20-day envelope midline; 5-day ETF flows beyond ±$250M; funding above 20% a year (−1); Fear & Greed at an extreme, ≤ 20 or ≥ 80 (−1); and 30-day exchange net flow beyond ±20,000 BTC.',
    why: 'A total of +3 or more reads Constructive, −2 or less Cautious, anything between Neutral. Below the label, each force — trend, liquidity and depth, leverage, flows, macro, sentiment — gets a verdict (supportive, neutral or headwind) with the numbers behind it; liquidity, leverage, flows and macro use the daily analysis’s own force scores, so this card and the Intelligence tab agree. The conclusion is assembled from those verdicts.',
    caveat: () => 'Rules-based summary of data on this page — not investment advice and not a forecast. The rules describe current conditions; they have no view on what price will do next.',
  },
  // ---- Market Intelligence Engine (engine/intel.js)
  i_read: {
    title: 'Market read',
    what: 'The engine’s one-word summary of Bitcoin’s market configuration on one five-step scale — Adverse, Cautionary, Neutral, Constructive or Supportive — built from five analytical domains: technical, on-chain, market structure, sentiment, and macro & liquidity.',
    why: 'It reads each of about 80 free indicators on its own scale, combines like with like inside each domain, and only then asks how many domains agree. Broad agreement across independent domains counts for more than any single strong signal.',
    caveat: () => 'A description of current conditions from public data — not investment advice and not a forecast. Open the Analysis tab to see every indicator behind it.',
  },
  i_grade: {
    title: 'Fair Grade',
    what: 'A 0–100 score of today’s overall market configuration. It starts at 50 and adds or subtracts explicit contributions: trend, demand, network and holders, liquidity, positioning, breadth, a risk adjustment and a valuation adjustment.',
    why: 'Unlike a plain average, it rewards breadth, penalises conflicting signals and stress, and scales every contribution by the confidence of the data behind it. The Intelligence tab shows each contribution.',
    caveat: () => 'Not a probability and not a price forecast: a summary of how supportive the current configuration is.',
  },
  i_forces: {
    title: 'Market forces',
    what: 'Forces are patterns the engine detects across indicators and domains — for example “Uptrend intact”, “Institutional demand”, “Leverage building” or “Macro tightening”. Only the forces active today are listed.',
    why: 'Each has a direction, strength, confidence, time horizon, persistence (how many days in a row it has been active) and whether it is strengthening or weakening. Ranking weighs strength by confidence and horizon, so a short-term derivatives signal cannot outweigh a long-term structural one on its own.',
    caveat: () => 'Detected by fixed published rules from free data; a force describes pressure, not an outcome.',
  },
  i_changes: {
    title: 'What changed',
    what: 'The engine recomputes itself as of 2, 7 and 30 days ago from stored history and compares the results with today.',
    why: 'Only indicators that have readings on both dates are compared, so a change in the result reflects the market, not a change in data coverage. The biggest single indicator moves are listed.',
    caveat: () => 'Inputs that only exist as a live snapshot (order books, options skew, news) cannot be compared over time and are left out of the comparison.',
  },
  i_valuation: {
    title: 'Valuation',
    what: 'A conclusion — Depressed, Attractive, Fair, Elevated or Extreme — drawn from several measures together: MVRV, the Mayer Multiple, price versus its 200-week average, the Puell Multiple, supply in profit and price versus short- and long-term holder cost bases.',
    why: 'No single metric decides it. Each is placed on a cheap-to-rich scale against its historical zones and weighted; demand and liquidity conditions are then used to say whether the valuation is likely to matter now.',
    caveat: () => 'Historical context, not a prediction. NVT and MVRV Z-Score are not available from free sources and are not used.',
  },
  i_cycle: {
    title: 'Market regime',
    what: 'Which market regime current conditions are consistent with — Bullish, Neutral or Bearish — with a description such as “an early uptrend” or “bear-market conditions”.',
    why: 'It is built from structural, medium- and long-horizon evidence across all five domains: the trend, price structure, holder positioning, on-chain flows, institutional demand, the liquidity backdrop, leverage and valuation room. The page lists which conditions are consistent with the description and which are not.',
    caveat: () => 'Time since the halving is never used. Regimes describe current conditions; they are not forecasts.',
  },
  i_risk: {
    title: 'Risk regime',
    what: 'How fragile conditions are, from Low to High, counted from stress signals: high realised or implied volatility, expensive or fast-growing leverage, rich valuations, equity and credit stress, sentiment extremes and cross-domain divergences.',
    why: 'A high risk regime means larger and faster moves are more likely — in either direction.',
    caveat: () => 'It says nothing about direction.',
  },
  i_confirm: {
    title: 'Cross-market confirmation',
    what: 'Where at least three independent domains point the same way (confirmation), and where domains or key signals disagree (divergence).',
    why: 'Agreement between independent sources is stronger evidence than any one indicator. Divergence is information too: it marks where the current read is most likely to be tested.',
  },
  i_tech: { title: 'Technical analysis', what: 'Price structure, trend, momentum, volatility and extension from daily closes: 20/50/100/200-day averages, RSI, MACD, Bollinger Bands, realised volatility, rate of change, highs and lows, drawdown and the Mayer Multiple.', why: 'The trend and its structure carry the most weight; momentum, extension and volatility refine the reading. A negative long-term trend caps this domain.' },
  i_chain: { title: 'On-chain analysis', what: 'What the network and its holders are doing: MVRV and the Puell Multiple, short- and long-term holder cost bases, SOPR, supply in profit, active addresses, transactions, fees, hash rate, hashprice, exchange flows and balances, large-holder balances and stablecoin supply.', why: 'Holder behaviour and exchange flows show whether coins are being accumulated or prepared for sale; stablecoins measure dollar liquidity already on crypto rails.' },
  i_mkt: { title: 'Market structure', what: 'What capital is doing: US spot ETF flows, CME positioning, perpetual funding, open interest and its growth versus price, futures basis, options skew and implied volatility, the Coinbase premium, spot taker flow, order-book balance, long/short ratios and BTC dominance.', why: 'Demand from ETFs and spot buyers is weighed against leverage; elevated leverage caps this domain because leveraged moves unwind quickly.' },
  i_sent: { title: 'Sentiment', what: 'What the market believes and pays attention to: the Fear & Greed level and its 7-day change, the tone and volume of recent headlines, and retail attention from Wikipedia pageviews.', why: 'Level, change and intensity are read separately. Extreme greed is read as crowded consensus rather than strength; extreme fear as contrarian support.', caveat: () => 'Google Trends and Reddit/X sentiment have no reliable free source and are not used.' },
  i_macro: { title: 'Macro & liquidity', what: 'The financial environment: US net liquidity, M2, the Fed/ECB/BoJ balance sheets, real and nominal yields, the 2-year yield as a proxy for rate expectations, the dollar, the VIX, high-yield spreads, the Nasdaq, Fed policy and inflation.', why: 'Bitcoin trades partly as a global liquidity asset; when its correlation with equities is high, these conditions matter more.' },
  d_dca: {
    title: 'DCA backtest',
    what: 'Dollar-cost averaging means buying a fixed dollar amount on a schedule, whatever the price. This page replays that plan on real daily closing prices for the period you choose and values what you would hold today at the live price.',
    why: 'It shows, with actual history rather than assumptions, how buying regularly averages your cost across good and bad prices.',
    caveat: () => 'Simulated at daily closes; real fills, spreads and fees differ. Past performance says nothing about future returns. Illustration only — not a recommendation to buy or sell.',
  },
  d_dcacmp: {
    title: 'DCA vs lump sum vs hindsight',
    what: 'The same total money invested two other ways: all of it on the first day of the period, and all of it on the single cheapest day of the period.',
    why: 'In a rising market a lump sum usually ends ahead because the money is invested longer; DCA reduces the risk of putting everything in at a bad moment. The hindsight line shows the best that was possible — and why nobody can do it.',
    caveat: () => 'The hindsight figure requires knowing the future and is shown only for scale.',
  },
  d_dcaroll: {
    title: 'Every window in history',
    what: 'The same plan, run for the same number of years, starting on every week in Bitcoin’s price history, each valued at the end of its own window.',
    why: 'One start date can be lucky or unlucky. Looking at every start date shows how much the outcome depended on timing.',
    caveat: () => 'Early years had a tiny, extremely volatile market that is unlikely to repeat; history is not a guide to the future.',
  },
  d_dcafwd: {
    title: 'If you keep this pace',
    what: 'How many more purchases, dollars and bitcoin the same plan adds over the next few years if every purchase happened at today’s price.',
    why: 'A way to see quantities — how many sats a habit adds — without pretending to know future prices.',
    caveat: () => 'Hypothetical: one constant price, not a forecast. It never shows a future value.',
  },
  d_etfs: {
    title: 'US spot Bitcoin ETFs',
    what: 'All 13 US-listed spot Bitcoin ETFs ranked by market value (each fund’s reported net assets) or by flows — the dollars of new shares created or redeemed, which the fund turns into bitcoin bought or sold. Includes Grayscale’s Mini Trust (BTC) and Hashdex (DEFI) alongside IBIT, FBTC, GBTC, BITB, ARKB, HODL, BRRR, EZBC, BTCO, BTCW and MSBT.',
    why: 'ETFs are one of the largest and most visible sources of spot demand: sustained inflows mean the funds are buying bitcoin, outflows mean they are selling.',
    caveat: () => 'Net assets come from Yahoo Finance and can lag a day or more; bitcoin held is estimated as net assets ÷ the live price. Flows come from Farside Investors and are published after the US close, some funds a day late. Hashdex (DEFI) is not in Farside’s table, so it has no flow figures.',
  },
  d_lightning: {
    title: 'Lightning Network',
    what: 'Public channels, nodes and total capacity of the Lightning Network, Bitcoin’s layer for fast, small payments.',
    why: 'Capacity shows how much bitcoin is committed to payment channels.',
    caveat: () => 'Only public channels are visible; private channels are not counted.',
  },
  d_fng: {
    title: 'Fear & Greed Index',
    what: 'A 0–100 score published by alternative.me that combines volatility, momentum, social media and other inputs into one sentiment reading.',
    why: 'Extreme readings show when the crowd is especially fearful or greedy.',
    caveat: () => 'A third-party index with its own method; BTC Intel shows it as published and does not compute it.',
  },
  d_news: {
    title: 'News & sentiment tags',
    what: 'Recent headlines from public RSS feeds. Each headline gets a bullish, bearish or neutral tag from a fixed list of keywords (for example “surges” or “outflows”).',
    why: 'A quick way to skim what the press is talking about and its tone.',
    caveat: () => 'Tags read words, not meaning — sarcasm, context or a headline about another asset can be mis-tagged. Hover a tag to see which words triggered it.',
  },
  d_moves: {
    title: 'Large moves',
    what: 'Single trades of $1 million or more on Coinbase, Binance and Kraken; liquidations of $100,000 or more on OKX and Bybit; and unconfirmed on-chain transactions moving 500 BTC or more.',
    why: 'Large prints show where big participants are active right now.',
    caveat: () => 'Only what this browser has seen while the page was open (kept for 24 hours). On-chain amounts include change sent back to the sender, so a large transaction is not necessarily a purchase or sale.',
  },
  d_converter: {
    title: 'Sats converter',
    what: 'One bitcoin is divided into 100 million satoshis (“sats”). This converts between dollars and sats at the live price.',
    why: 'Many everyday Bitcoin amounts are easier to think about in sats.',
  },
  d_lastvisit: {
    title: 'Since your last visit',
    what: 'How a few headline figures changed since you last had this page open in this browser.',
    why: 'A quick catch-up without reading every card.',
    caveat: () => 'Stored only in your browser; nothing is sent anywhere.',
  },
};
