// Research notes for the Analysis deep dives: what each indicator measures, why it matters,
// how the engine reads it, when it misleads, and related indicators. Plain English, no
// predictions. Keys are indicator ids from engine/intel.js.

export const DOMAIN_DOCS = {
  tech: {
    overview: 'Technical analysis studies price itself: its trend across several time frames, the speed of moves (momentum), the shape of highs and lows (structure), how far price has run from its averages (extension) and how violently it moves (volatility). All inputs are computed from daily closing prices since 2010.',
    role: 'The trend carries the most weight; momentum, structure, extension and volatility refine it. A negative long-term trend caps the domain, and a strong but stretched trend is capped below Supportive.',
  },
  chain: {
    overview: 'On-chain analysis reads the Bitcoin ledger: what holders paid for their coins (realised value and cost bases), whether they are taking profits, how actively the network is used, what miners earn, whether coins are moving onto or off exchanges, and how much dollar liquidity sits on crypto rails as stablecoins.',
    role: 'Valuation and holder behaviour carry the most weight, followed by exchange behaviour, stablecoin liquidity and network activity. Expensive on-chain valuation caps the domain.',
  },
  mkt: {
    overview: 'Market structure describes what is happening inside the Bitcoin and crypto market itself: institutional demand through spot ETFs and CME, spot buying, leverage in perpetual futures, the futures and options curve, positioning ratios, order-book depth and the balance between Bitcoin and the rest of crypto.',
    role: 'Institutional and spot demand are weighed against leverage. Elevated leverage caps the domain, because leveraged moves unwind quickly. External financial conditions belong to Macro & Liquidity, not here.',
  },
  sent: {
    overview: 'Sentiment measures what the market believes and pays attention to: the Fear & Greed index, the tone and volume of news, and public attention measured by Wikipedia pageviews. Level, change and intensity are read separately.',
    role: 'Extremes are read in context: extreme greed counts as crowded consensus, extreme fear as contrarian support. Extreme greed overrides the other sentiment inputs.',
  },
  macro: {
    overview: 'Macro & Liquidity describes the financial environment Bitcoin trades in: how much dollar and central-bank liquidity is in the system, the level and direction of interest rates and inflation, the strength of the dollar, broad financial conditions and credit stress, and risk appetite in equities.',
    role: 'Liquidity carries the most weight, followed by rates and the dollar, then financial conditions and risk appetite. When Bitcoin trades closely with equities, this domain matters more than usual.',
  },
};

export const COMP_DOCS = {
  Trend: 'Direction of price across short, medium and long horizons: price versus its 20/50/100/200-day averages and the slope of the long-term average.',
  Momentum: 'Speed and persistence of moves: RSI, MACD, rates of change and whether volume confirms the move.',
  Structure: 'Shape of the market: higher or lower highs and lows, where price sits in its recent range and how far it is below its all-time high.',
  Extension: 'How far price has run from its own averages: the Mayer Multiple, distance from the 20-day mean and RSI extremes. Stretched readings raise the odds of pauses, not of reversals per se.',
  Volatility: 'How violently price moves: realised volatility, Bollinger Band width and the average daily move, each against its own past year.',
  Valuation: 'Price against the network’s aggregate cost basis: MVRV, MVRV Z-Score, realised price and capitalisation, NUPL and the Puell Multiple.',
  'Holder behaviour': 'Whether recent and long-term holders are in profit and whether they are realising it: short- and long-term holder cost bases, SOPR and supply in profit.',
  'Network activity': 'Use and security of the network: active addresses, transactions, fees, hash rate and miner revenue.',
  'Exchange behaviour': 'Net movement of coins onto or off exchanges, a proxy for supply prepared for sale versus moved to custody.',
  'Supply dynamics': 'How much supply sits on exchanges and what the largest holders are doing.',
  'On-chain liquidity': 'Dollar stablecoins on crypto rails: total supply and the two largest issuers.',
  'Institutional demand': 'US spot ETF flows, ETF assets, corporate treasuries and CME asset-manager positioning.',
  Leverage: 'Cost and size of leverage: perpetual funding, open interest relative to price and to market cap, and liquidations.',
  Derivatives: 'The futures and options curve: basis, 25-delta skew, put/call ratio and implied volatility.',
  'Spot demand': 'Buying in the spot market: the Coinbase premium, aggressor (taker) flow, order-book balance and spot volume.',
  'Market positioning': 'How traders are leaning: long/short account ratios and CME leveraged-fund positioning.',
  'Crypto market structure': 'Bitcoin versus the rest of crypto: dominance, altcoin breadth and the stablecoin share of crypto market value.',
  'Fear & Greed': 'The level of the composite Fear & Greed index, its recent change and its 30-day regime.',
  News: 'Tone of recent Bitcoin headlines from public RSS feeds, tagged by fixed keyword rules.',
  'Retail attention': 'Public curiosity measured by daily views of the English Wikipedia “Bitcoin” article (Google Trends has no free API).',
  Narrative: 'Intensity of coverage, dominant headline themes and prediction-market activity (context only).',
  Liquidity: 'Dollar and central-bank liquidity: US net liquidity, M2, the Fed balance sheet (QT/QE) and the Fed + ECB + BoJ balance sheets in dollars.',
  'Rates & policy': 'Interest rates and the policy backdrop: real and nominal yields, the 2-year yield as a proxy for rate expectations, the fed funds rate, the yield curve and inflation.',
  Dollar: 'Strength and momentum of the US dollar index.',
  'Financial conditions': 'Broad financial conditions and stress: the Chicago Fed NFCI, high-yield credit spreads and the VIX.',
  'Risk appetite': 'Demand for risk assets: the Nasdaq 100, S&P 500 and global equities, with gold and the BTC–Nasdaq correlation as context.',
};

const D = (what, why, caveat, related = [], reading = null) => ({ what, why, caveat, related, reading });
export const IND_DOCS = {
  // ---- technical
  t_ma200: D('The percentage distance between today’s price and its average closing price over the last 200 days, the most widely watched long-term trend line.', 'Bitcoin bull markets have historically held above a rising 200-day average and bear markets below a falling one; crossing it often marks a change of regime.', 'In sharp V-shaped reversals the average lags badly, and in sideways markets price whips around it.', ['t_slope200', 't_ma50_200', 't_mayer', 't_ma100'], 'Supportive the further price sits above the average (full weight from about +12%), cautionary below it.'),
  t_ma50_200: D('The gap between the 50-day and 200-day moving averages (a “golden cross” when the 50-day moves above).', 'It summarises whether the medium-term trend agrees with the long-term one.', 'Crosses lag: by the time they occur much of the move has often happened.', ['t_ma200', 't_ma20_50', 't_slope200'], 'Supportive when the 50-day sits above the 200-day, scaled to about ±6%.'),
  t_slope200: D('How much the 200-day average itself has changed over the last 30 days.', 'A rising long-term average means the trend is still advancing even when price pulls back.', 'It turns slowly and can keep rising for weeks after a top.', ['t_ma200', 't_ma50_200'], 'Supportive when rising (full weight at about +3% a month), cautionary when falling.'),
  t_ma20_50: D('The gap between the 20-day and 50-day averages, a short-term trend gauge.', 'It shows whether the most recent weeks are adding to or working against the medium-term trend.', 'Noisy; it flips often in ranges.', ['t_ma50_200', 't_roc30', 't_macd']),
  t_ma100: D('Price relative to its 100-day average.', 'A medium-term trend check between the 50- and 200-day.', 'Shares most of its information with the other averages.', ['t_ma200', 't_ma50_200']),
  t_rsi: D('The Relative Strength Index compares the size of recent up-days with down-days over 14 days, on a 0–100 scale.', 'It measures the strength of momentum; persistent readings above 50 accompany uptrends.', 'In strong trends RSI can stay “overbought” or “oversold” for weeks; on its own it is a poor timing tool.', ['t_rsiext', 't_macd', 't_roc30'], 'Momentum: supportive above 50 (peaking around 70), cautionary below 45. Very high readings are scored separately as extension.'),
  t_macd: D('MACD is the gap between the 12- and 26-day exponential averages; its signal line is a 9-day average of that gap, and the histogram is the difference.', 'It shows whether momentum is building or fading and is widely used to spot turns in momentum.', 'It lags and generates many false signals in sideways markets.', ['t_rsi', 't_roc30', 't_ma20_50']),
  t_roc30: D('The percentage change in price over 30 days.', 'Simple, transparent one-month momentum.', 'Sensitive to the starting point: a big move exactly 30 days ago distorts it.', ['t_roc90', 't_rsi']),
  t_roc90: D('The percentage change in price over 90 days.', 'Three-month momentum, closer to the medium-term trend.', 'Sensitive to the starting point.', ['t_roc30', 't_ma200']),
  t_volume: D('Average daily spot volume over the last 7 days relative to the last 30, signed by the direction of the 7-day price move.', 'Moves on rising volume are better supported than moves on fading volume.', 'Aggregate volume mixes venues and includes wash trading on some exchanges.', ['m_spotvol', 't_roc30']),
  t_hhhl: D('Whether the highest and lowest closes of the last 30 days are above or below those of the 30 days before.', 'Higher highs and higher lows define an orderly uptrend; lower highs and lower lows a downtrend.', 'A single spike can flip the comparison.', ['t_range', 't_dd']),
  t_range: D('Where price sits between its lowest and highest close of the last 90 days (0% = at the low, 100% = at the high).', 'It locates price inside its recent range.', 'Says nothing about the size of the range.', ['t_hhhl', 't_levels']),
  t_dd: D('The percentage distance below the highest daily close ever recorded (distance from the all-time high).', 'It shows how much of the prior advance has been given back and how damaged the structure is.', 'Bitcoin’s history includes several drawdowns of 75–85%; moderate drawdowns are normal inside uptrends.', ['t_hhhl', 't_ma200']),
  t_levels: D('The nearest recent turning points in daily closes above and below price (local highs and lows over ±7 days in the last 180 days).', 'Previous turning points are where buyers or sellers acted before.', 'Context only; levels are not scored and are not forecasts.', ['t_range']),
  t_mayer: D('The Mayer Multiple: price divided by its 200-day average.', 'It measures how extended price is from its long-term trend; historically, very high readings coincided with late-cycle conditions.', 'The threshold that marked tops has drifted lower as Bitcoin matured.', ['t_ma200', 'c_mvrv', 't_bbz'], 'Not extended below 1.25; stretched from about 1.5; very stretched above 2.0.'),
  t_bbz: D('How many standard deviations price is from its 20-day average (the Bollinger Band position).', 'It flags short-term stretch: closes outside the bands are statistically unusual.', 'In strong trends price can “walk the band” for days.', ['t_bbw', 't_rsiext', 't_mayer']),
  t_rsiext: D('RSI read for extremes only: very high (above ~72) or very low (below ~30).', 'Extremes mark short-term stretch or exhaustion.', 'Extremes can persist in strong trends.', ['t_rsi', 't_bbz']),
  t_rv: D('Realised volatility: the annualised standard deviation of daily log returns over 30 days, and its percentile over the past year.', 'High volatility means disorderly moves and larger swings in either direction; low volatility often precedes expansions.', 'Backward-looking: it measures what happened, not what will.', ['t_bbw', 't_atr', 'm_dvol', 't_hv']),
  t_bbw: D('The width of the Bollinger Bands (four standard deviations of the last 20 closes) as a share of price, with its percentile over the past year.', 'Compressed bands mean a quiet market that historically tends to resolve in a larger move.', 'Says nothing about the direction of the next move.', ['t_rv', 't_bbz']),
  t_atr: D('The average absolute daily change over 14 days, as a share of price (computed close-to-close, because free data has no reliable intraday highs and lows).', 'A practical measure of how much price typically moves in a day.', 'Close-to-close values understate the classic true-range ATR.', ['t_rv']),
  t_hv: D('Realised volatility over the full past year.', 'A baseline to compare current volatility with.', 'Context only.', ['t_rv']),
  // ---- on-chain
  c_mvrv: D('MVRV is market capitalisation divided by realised capitalisation: what the market values Bitcoin at, versus what holders collectively paid for their coins.', 'It is one of the most robust cycle measures: readings near or below 1 historically marked deep value, readings above 3 late-cycle euphoria.', 'Lost coins and long-dormant supply inflate realised gains; peaks have been lower in each cycle.', ['c_mvrvz', 'c_realized', 'c_nupl', 'c_rcap'], 'Attractive below about 1.6, neutral to about 2.4, increasingly expensive above; deep value below 1.'),
  c_realized: D('Realised price: realised capitalisation divided by supply, the average price at which every coin last moved.', 'It is the network’s aggregate cost basis; price below it means the average holder is at a loss.', 'Same information as MVRV, so shown as context and not scored twice.', ['c_mvrv', 'c_sth', 'c_lth']),
  c_nupl: D('Net unrealised profit/loss: the share of market value that is unrealised profit (1 − 1/MVRV).', 'Its bands (capitulation, hope, optimism, belief, euphoria) are a common way to describe the cycle.', 'Mathematically derived from MVRV; context only.', ['c_mvrv']),
  c_mvrvz: D('MVRV Z-Score: the gap between market cap and realised cap, divided by the standard deviation of market cap over all history to date. Computed here from Coin Metrics supply, price and MVRV.', 'It normalises the MVRV gap by Bitcoin’s own volatility; historically extremes marked cycle tops (high) and bottoms (low).', 'Older history is sampled weekly; the standard deviation grows over time, so recent peaks are lower.', ['c_mvrv', 'c_rcap']),
  c_rcap: D('Realised capitalisation: the value of every coin at the price it last moved (market cap ÷ MVRV).', 'It measures the capital actually stored in the network; it rises when coins change hands at higher prices.', 'Context only.', ['c_mvrv', 'c_realized']),
  c_mvrvtr: D('Today’s MVRV relative to its own average over the past year.', 'It shows whether holders’ unrealised profit is building or eroding — the direction of on-chain positioning rather than its level.', 'Can stay positive through long, slow tops; it is a direction gauge, not a valuation.', ['c_mvrv', 'c_sth', 'c_profit']),
  c_ribbons: D('Hash Ribbons: the 30-day average hash rate divided by the 60-day average (Coin Metrics). A recovery is the 30-day crossing back above the 60-day after at least ten days below it.', 'Falling hash rate means miners are switching off under financial stress and may be selling coins; a recovery has historically marked the end of miner capitulation.', 'Hash-rate estimates are noisy; difficulty adjustments and energy events (heat waves, curtailment) cause dips unrelated to markets.', ['c_hash', 'c_hashprice', 'c_puell']),
  c_puell: D('The Puell Multiple: the dollar value of coins issued to miners today relative to its one-year average.', 'Low readings mean miners earn little versus the past year (historically near cycle lows); high readings the opposite.', 'Halvings cut issuance in half overnight and distort the ratio for a year.', ['c_hashprice', 'c_hash', 'c_mvrv']),
  c_sth: D('Price relative to the short-term holder realised price, the average cost of coins that moved in the last ~155 days.', 'Recent buyers react to their cost basis: above it, dips tend to find support; below it, rallies meet break-even selling.', 'The free BGeometrics data is about a week delayed.', ['c_lth', 'c_sopr', 'c_realized']),
  c_lth: D('Price relative to the long-term holder realised price, the average cost of coins held longer than ~155 days.', 'Long-term holders distribute into strength; very high multiples historically coincided with distribution.', 'Delayed about a week in the free data.', ['c_sth', 'c_mvrv']),
  c_sopr: D('Spent Output Profit Ratio (7-day average): the price at which coins moved divided by the price at which they were acquired.', 'Above 1, coins are sold at a profit; below 1, at a loss. Sustained readings below 1 have marked capitulation.', 'Exchange-internal movements add noise.', ['c_profit', 'c_sth']),
  c_profit: D('The share of all coins whose last-moved price is below the current price.', 'Very high shares mean many holders could take profits; low shares mean sellers are exhausted.', 'Near all-time highs it is mechanically close to 100%.', ['c_sopr', 'c_mvrv']),
  c_active: D('The 30-day average of daily active addresses relative to the 90-day average.', 'A rough gauge of network use and new participation.', 'Address counts are not users: batching and exchange behaviour change them.', ['c_tx', 'c_fees']),
  c_tx: D('The 30-day average of daily transactions relative to the 90-day average.', 'Demand for blockspace.', 'Inscriptions and batching can move it for reasons unrelated to investment demand.', ['c_active', 'c_fees']),
  c_fees: D('Fees paid to miners over 30 days relative to 90 days.', 'Willingness to pay for settlement; spikes accompany congestion.', 'Fee spikes from non-monetary activity can mislead.', ['c_tx', 'c_hashprice']),
  c_hash: D('The 30-day change in the 7-day average hash rate.', 'Rising hash rate means miners keep investing; sharp falls can signal miner stress.', 'Hash rate is estimated from block times and is noisy day to day.', ['c_hashprice', 'c_puell']),
  c_hashprice: D('Hashprice: expected miner revenue per petahash per day, and its 30-day change.', 'Squeezed miner revenue can force miners to sell coins.', 'Depends on fees, price and difficulty together.', ['c_hash', 'c_puell']),
  c_exnet: D('Net BTC flowing onto exchanges (inflows minus outflows) over 30 days.', 'Persistent outflows suggest coins moving to custody (accumulation); inflows suggest supply prepared for sale.', 'Exchange wallet labelling is imperfect, and ETF custody flows can appear as exchange movements.', ['c_exbal', 'c_whales']),
  c_exbal: D('The 30-day change in the BTC balance held on exchanges.', 'Falling balances tighten the liquid supply available to sell.', 'Labelling changes and wallet reshuffles can cause jumps.', ['c_exnet', 'c_whales']),
  c_whales: D('The 30-day change in BTC held by addresses with 1,000 BTC or more (BitInfoCharts rich list).', 'Large holders adding is read as accumulation.', 'Includes exchange and custodian wallets; history accumulates from daily snapshots.', ['c_exbal', 'c_exnet']),
  c_stab30: D('The 30-day change in total dollar-stablecoin supply.', 'Stablecoins are dollar liquidity already on crypto rails; growth means more capital ready to deploy.', 'Some supply sits idle or in other chains’ DeFi.', ['c_stab7', 'c_usdt', 'x_netliq4']),
  c_stab7: D('The 7-day change in total stablecoin supply.', 'Short-term issuance or redemption.', 'Noisy week to week.', ['c_stab30']),
  c_usdt: D('The 30-day supply change of USDT and USDC, the two largest dollar stablecoins.', 'They dominate stablecoin liquidity in crypto trading.', 'Current snapshot only; history accumulates.', ['c_stab30']),
  // ---- market structure
  m_etf5: D('Net creations minus redemptions across US spot Bitcoin ETFs over the last five trading days (Farside Investors).', 'ETF flows are the clearest public measure of institutional spot demand since 2024.', 'Part of the flow is hedged basis trading (long ETF, short CME futures), which is not directional demand.', ['m_etf20', 'm_etfacc', 'm_etfcum', 'm_cftclev']),
  m_etf20: D('Net ETF flows over the last twenty trading days.', 'The persistent part of institutional demand.', 'Needs 20 stored trading days; appears automatically once the history exists.', ['m_etf5', 'm_etfcum']),
  m_etfacc: D('The average daily ETF flow over the last 5 days minus that of the last 20.', 'Shows whether institutional demand is accelerating or fading.', 'Small samples; a single large day dominates.', ['m_etf5', 'm_etf20']),
  m_etfcum: D('The running total of net ETF flows over the days stored.', 'Shows the direction of institutional demand across the window.', 'Not since-launch unless the full history is available.', ['m_etf5', 'm_etfaum']),
  m_etfweeks: D('Consecutive weeks of net ETF inflows or outflows.', 'Persistence of institutional demand.', 'Context only.', ['m_etf20']),
  m_etfaum: D('Total assets of US spot Bitcoin ETFs (Yahoo Finance).', 'Size of the institutional wrapper.', 'Moves with price as well as flows.', ['m_etfcum']),
  m_treas: D('Bitcoin held on public-company balance sheets.', 'A slow-moving source of structural demand.', 'Context only.', ['m_etfaum']),
  m_cftcam: D('The weekly change in CME Bitcoin futures net positioning of asset managers (CFTC Commitments of Traders).', 'Regulated, institutional positioning.', 'Weekly and published with a lag.', ['m_cftclev', 'm_etf5']),
  m_funding: D('The annualised rate longs pay shorts (or vice versa) to keep perpetual futures near spot.', 'High positive funding means crowded leveraged longs; negative funding means shorts are paying, which can fuel squeezes.', 'Venues differ; brief spikes are common.', ['m_oigrowth', 'm_oimcap', 'm_basis'], 'Healthy at 0–8% a year; crowded above about 20%; negative is read as contrarian support.'),
  m_oigrowth: D('Open-interest growth over 30 days minus price growth over the same period (OKX history).', 'Open interest rising much faster than price means the move leans on new leverage.', 'Single-venue proxy for the aggregate.', ['m_funding', 'm_oimcap', 'm_liq']),
  m_oimcap: D('Aggregate futures open interest as a share of Bitcoin’s market cap.', 'How much leverage sits on the asset relative to its size.', 'Coverage depends on which venues respond.', ['m_oigrowth', 'm_funding']),
  m_liq: D('Forced closures of leveraged positions in the latest public sample.', 'Large long liquidations mark capitulation; large short liquidations mark squeezes.', 'A sample from one venue, not the market total.', ['m_oigrowth']),
  m_basis: D('The annualised premium of ~3-month futures over spot (Deribit).', 'A normal positive carry signals healthy demand; a rich basis signals leveraged enthusiasm; a negative basis stress.', 'Basis trades by ETF hedgers compress it.', ['m_funding', 'm_skew']),
  m_skew: D('Options 25-delta skew: implied volatility of 25-delta calls minus puts at ~30 days (negative = puts richer).', 'Shows whether traders pay up for downside protection or upside exposure.', 'Snapshot of one venue (Deribit); history accumulates daily.', ['m_pcr', 'm_dvol', 'm_ivrv']),
  m_pcr: D('Open interest in puts divided by calls.', 'A rough gauge of hedging demand.', 'Puts are also used in income strategies; context matters.', ['m_skew']),
  m_dvol: D('Deribit’s 30-day implied volatility index (DVOL) and its percentile over the past year.', 'The price of protection: high values mean the options market expects turbulence.', 'Implied volatility often rises after moves, not before.', ['t_rv', 'm_skew', 'm_ivrv']),
  m_ivrv: D('Implied volatility minus realised volatility.', 'Shows whether options are cheap or expensive relative to actual movement.', 'Context only.', ['m_dvol', 't_rv']),
  m_cbp: D('The price gap between Coinbase BTC-USD and offshore BTC-USDT venues.', 'A widely used proxy for US (and institutional) spot demand.', 'Tiny in absolute terms; affected by USDT’s own peg.', ['m_taker', 'm_etf5']),
  m_taker: D('The ratio of aggressive buying to aggressive selling in OKX spot over 7 days.', 'Shows which side is crossing the spread.', 'One venue.', ['m_cbp', 'm_depth']),
  m_depth: D('Bid versus ask depth within ±1% of price across major order books.', 'Resting liquidity shapes how far price moves per dollar traded.', 'Displayed liquidity can be pulled instantly.', ['m_taker']),
  m_spotvol: D('Aggregate 24-hour spot volume and the ratio of derivatives to spot volume.', 'Activity level and how derivatives-driven the market is.', 'Context only.', ['t_volume']),
  m_ls: D('The ratio of accounts net long to accounts net short on OKX perpetuals.', 'High ratios mean retail is crowded long, read contrarian.', 'Counts accounts, not position size.', ['m_funding', 'm_cftclev']),
  m_cftclev: D('CME net position of leveraged funds (CFTC).', 'Mostly the short leg of ETF basis trades.', 'Context, not direction.', ['m_cftcam', 'm_etf5']),
  m_dom: D('Bitcoin’s share of total crypto market capitalisation, and its 7-day change.', 'Rising dominance means capital is concentrating in Bitcoin rather than rotating into altcoins.', 'Stablecoin growth mechanically lowers it.', ['m_breadth', 'm_stabdom']),
  m_breadth: D('The share of the top coins that outperformed Bitcoin over 30 days.', 'Broad altcoin outperformance signals speculative rotation.', 'Context only.', ['m_dom']),
  m_stabdom: D('Stablecoins as a share of crypto market value.', 'More capital parked in dollars inside crypto.', 'Context only.', ['m_dom', 'c_stab30']),
  // ---- sentiment
  s_fng: D('The Crypto Fear & Greed Index (0–100) from alternative.me, combining volatility, momentum, social and survey inputs, with its percentile.', 'A widely followed summary of crowd mood; extremes are informative in a contrarian way.', 'Its inputs overlap with price momentum; it is third-party and its method is only partly public.', ['s_fngchg', 's_fngreg', 's_wiki'], 'Extreme fear (≤25) is read as contrarian support; extreme greed (≥85) as crowding.'),
  s_fngchg: D('The 7-day change in the Fear & Greed index (sentiment momentum).', 'Separates the direction of mood from its level; rising greed from a high level is read as overheating.', 'Noisy.', ['s_fng']),
  s_fngreg: D('The 30-day average of the index.', 'The sentiment regime behind the daily figure.', 'Context only.', ['s_fng']),
  s_news: D('The balance of positive and negative tags across Bitcoin headlines from the last 48 hours (public RSS feeds, fixed keyword rules).', 'A transparent read of news tone.', 'Keyword tags miss nuance and sarcasm; this is not an assessment of the stories.', ['s_newsvol', 's_themes']),
  s_newsvol: D('Headlines in the last 24 hours versus the average day over 72 hours (narrative intensity).', 'Surging coverage marks a dominant story.', 'Current snapshot only.', ['s_news', 's_themes']),
  s_themes: D('The most frequent tagged words in recent headlines.', 'Shows what the narrative is about.', 'Context only.', ['s_news']),
  s_pm: D('Active Bitcoin price markets on Polymarket.', 'Market-implied odds are shown on the dashboard.', 'Not scored; odds are not BTCIntel’s forecast.', []),
  s_wiki: D('Average daily human views of the English Wikipedia “Bitcoin” article over 7 days relative to 90 days.', 'A free, public proxy for retail attention (search interest has no free API). Spikes accompany frenzies and panics.', 'English-language only; bots are filtered by Wikimedia but not perfectly.', ['s_wikitr', 's_fng']),
  s_wikitr: D('Average views over 30 days relative to 90 days.', 'The slower trend in public interest.', 'As above.', ['s_wiki']),
  // ---- macro & liquidity
  x_netliq4: D('US net liquidity — Fed total assets minus the Treasury General Account minus overnight reverse repo — and its 4-week change (FRED).', 'A widely used proxy for dollar liquidity available to markets; it has tracked risk assets including Bitcoin.', 'Weekly data; the relationship with prices is loose and varies over time.', ['x_netliq13', 'x_fed', 'x_g3', 'x_m2']),
  x_netliq13: D('US net liquidity, 13-week change.', 'The slower trend in dollar liquidity.', 'As above.', ['x_netliq4', 'x_fed']),
  x_m2: D('Year-on-year growth of US M2 money supply (FRED, monthly).', 'Broad money growth is a long-horizon tailwind for scarce assets.', 'Monthly and published with a lag of several weeks.', ['x_g3', 'x_netliq4']),
  x_g3: D('Global liquidity proxy: the combined balance sheets of the Fed, ECB and Bank of Japan converted to US dollars, and their 13-week change.', 'Captures central-bank liquidity beyond the US, including currency effects.', 'BoJ data are monthly and lag; currency moves alone change the dollar total.', ['x_fed', 'x_netliq4', 'x_m2', 'x_dxy']),
  x_fed: D('The 13-week change in the Federal Reserve’s total assets (quantitative tightening when falling, easing when rising).', 'Balance-sheet policy changes the supply of reserves and liquidity.', 'Its effect on markets depends also on the Treasury account and reverse repo.', ['x_netliq4', 'x_g3']),
  x_real: D('The 4-week change in the 10-year TIPS (real) yield.', 'Real yields are the opportunity cost of holding a non-yielding asset; rising real yields have weighed on Bitcoin and gold.', 'The link weakens when Bitcoin trades on its own drivers.', ['x_reallvl', 'x_10y', 'x_2y', 'x_dxy']),
  x_reallvl: D('The level of the 10-year real yield.', 'High real yields mean safe assets pay well after inflation.', 'Context only.', ['x_real']),
  x_2y: D('The 4-week change in the 2-year Treasury yield, the market’s best free proxy for expected Fed policy.', 'Falling 2-year yields mean markets are pricing rate cuts.', 'Also reflects risk-off flight to safety.', ['x_ff', 'x_real']),
  x_10y: D('The 4-week change in the 10-year Treasury yield.', 'Long-term borrowing costs.', 'Mixes inflation, growth and term premium.', ['x_real', 'x_curve']),
  x_ff: D('The 6-month change in the effective fed funds rate.', 'The direction of monetary policy.', 'Changes only at FOMC meetings.', ['x_2y', 'x_cpi']),
  x_curve: D('The 10-year minus 2-year Treasury spread.', 'Inversion historically preceded slowdowns and rate cuts.', 'Context only; timing is very loose.', ['x_2y', 'x_10y']),
  x_cpi: D('US CPI inflation, year on year, and its 3-month change.', 'Inflation sets how much room the Fed has to ease.', 'Monthly, lagged, revised.', ['x_pce', 'x_be', 'x_ff']),
  x_pce: D('Core PCE inflation, year on year.', 'The Fed’s preferred inflation gauge.', 'Context only.', ['x_cpi']),
  x_be: D('The 10-year breakeven inflation rate (nominal minus real yield).', 'Market expectations of inflation.', 'Context only.', ['x_cpi', 'x_real']),
  x_unrate: D('The US unemployment rate and its 3-month change.', 'Labour-market slack shapes policy.', 'Context only; rising unemployment can mean cuts and weaker growth at the same time.', ['x_ff']),
  x_gdp: D('US real GDP growth, quarter on quarter, annualised.', 'The growth backdrop.', 'Quarterly and revised.', []),
  x_nfci: D('The Chicago Fed National Financial Conditions Index: a weekly composite of 105 measures of risk, credit and leverage. Negative values mean looser than average conditions.', 'Loose financial conditions support risk-taking; tightening conditions often precede stress.', 'Weekly; it moves slowly and is revised.', ['x_hy', 'x_vix', 'x_real']),
  x_vix: D('The VIX, the implied volatility of S&P 500 options.', 'A measure of equity-market stress; spikes coincide with broad deleveraging that usually hits Bitcoin too.', 'Equity-specific.', ['x_hy', 'x_nfci', 'm_dvol']),
  x_hy: D('The 4-week change in the US high-yield option-adjusted spread (ICE BofA via FRED).', 'Widening credit spreads signal rising risk aversion and funding stress.', 'Daily data, published with a short lag.', ['x_nfci', 'x_vix']),
  x_ndx: D('The 4-week change in the Nasdaq 100.', 'Growth equities are the risk asset Bitcoin has most often traded with.', 'The link with Bitcoin varies; see the correlation.', ['x_corr', 'x_spx', 'x_acwi']),
  x_spx: D('The 4-week change in the S&P 500.', 'Broad US risk appetite.', 'As above.', ['x_ndx', 'x_acwi']),
  x_acwi: D('The 4-week change in the iShares MSCI ACWI ETF, a proxy for global equities.', 'Risk appetite beyond the US.', 'An ETF in dollars, so the dollar affects it.', ['x_spx', 'x_dxy']),
  x_gold: D('The 4-week change in gold.', 'Demand for the traditional hedge.', 'Context only.', ['x_real', 'x_dxy']),
  x_corr: D('The 30-day correlation of daily Bitcoin and Nasdaq returns.', 'When it is high, macro and equity moves matter more for Bitcoin.', 'Correlations are unstable and say nothing about cause.', ['x_ndx']),
  x_dxy: D('The 4-week change in the US dollar index (DXY).', 'A firmer dollar tightens global financial conditions and has tended to weigh on Bitcoin.', 'DXY is weighted heavily toward the euro.', ['x_dxytr', 'x_g3', 'x_real']),
  x_dxytr: D('The dollar index relative to its 200-day average (dollar trend).', 'The slower trend in the dollar.', 'As above.', ['x_dxy']),
};
